### ISSUE TITLE
When you remove a group, the "/c perm" command will continue to list that group as an exception.

### ISSUE THREAD

**Issue by D4rknessKing** [GameModsBR/MineCity#78] opened 2016-11-13 23:37 UTC
![javaw_2016-11-13_20-32-36](https://cloud.githubusercontent.com/assets/21957862/20249844/e443f592-a9e0-11e6-9e29-3b95f4c11d60.png)

**Comment by joserobjr** [comment] 2016-11-14 09:19
I could not reproduce this issue.

To completely remove a permission/restriction you need to type the reset command.
In Portuguese:
/cidade resetar modificar Yalux Construtor
/cidade resetar modificar Yalux Vice-Prefeito

**Comment by joserobjr** [comment] 2016-11-14 22:54
Oh, I got what you mean now, you have removed the group Yalux from the city but it was still there on the permissions.

This was related to #87 #58 and #88 and was fixed on commit 31739f1c35a9f76de2c476312e9794c0bb797f87

Thank you for reporting :+1:

**Closed by joserobjr** 2016-11-14 22:54 UTC
Labels: S: Core, T: Bug

**Comment by D4rknessKing** [comment] 2016-11-15 00:05
Actually, the city was named "Yalux" and the deleted group that continued to show on the permissions was named "Construtor"... But i think you got the point 😄
